"use strict";
exports.__esModule = true;
exports.myname = void 0;
exports.myname = "lê quý vương";
var myAge = 2;
var status = true;
var myObj = {};
var numberArr = [1, 2, 3, 4];
var object = {};
var arrObject = [{ id: 1 }, { id: 2 }, { id: 3 }];
